// Actions
export const GET_LATEST_DATA = "GET_LATEST_DATA";

export const GET_ORGANISATION_SUMMARIES = "GET_ORGANISATION_SUMMARIES";
export const GET_ORGANISATION_EVENTS = "GET_ORGANISATION_EVENTS";
export const GET_EVENT_SUMMARIES = "GET_EVENT_SUMMARIES";

export const GET_ORGANISATION_SUMMARIES_SUCCESS = "GET_ORGANISATION_SUMMARIES_SUCCESS";
export const GET_ORGANISATION_EVENTS_SUCCESS = "GET_ORGANISATION_EVENTS_SUCCESS";
export const GET_EVENT_SUMMARIES_SUCCESS = "GET_EVENT_SUMMARIES_SUCCESS";

export const CA_DASHBOARD_API_ERROR = "CA_DASHBOARD_API_ERROR";