version: "3"

services:
    esg_frontend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 54434:80
        environment:
        - PORTAL_URL=http://218.255.16.134:54433/v1