export const GET_EVENTS = "GET_EVENTS"
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS"
export const API_EVENT_ERROR = "API_EVENT_ERROR"

export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS'
export const GET_EVENT_DETAILS_SUCCESS = 'GET_EVENT_DETAILS_SUCCESS'

export const GET_EVENT_NATURE = 'GET_EVENT_NATURE'
export const GET_EVENT_NATURE_SUCCESS = 'GET_EVENT_NATURE_SUCCESS'

export const UPDATE_EVENT = 'UPDATE_EVENT'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'

export const CREATE_EVENT = 'CREATE_EVENT'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'

export const DELETE_EVENT = 'DELETE_EVENT'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
