// Actions
export const GET_LATEST_DATA = "GET_LATEST_DATA";
export const GET_LATEST_DATA_SUCCESS = "GET_LATEST_DATA_SUCCESS";
export const GET_LATEST_DATA_ERROR = "GET_LATEST_DATA_ERROR";

export const GET_RECORDING_PERIOD = 'GET_RECORDING_PERIOD';
export const GET_RECORDING_PERIOD_SUCCESS = 'GET_RECORDING_PERIOD_SUCCESS';
