export const GET_COINS_HISTORY = "GET_COINS_HISTORY"
export const GET_COINS_HISTORY_SUCCESS = "GET_COINS_HISTORY_SUCCESS"
export const COINS_API_ERROR = "COINS_API_ERROR"

export const GET_COINS_SUMMARY = 'GET_COINS_SUMMARY'
export const GET_COINS_SUMMARY_SUCCESS = 'GET_COINS_SUMMARY_SUCCESS'