export const GET_PRIZES = "GET_PRIZES"
export const GET_PRIZES_SUCCESS = "GET_PRIZES_SUCCESS"
export const PRIZE_API_ERROR = "PRIZE_API_ERROR"

export const GET_PRIZE = "GET_PRIZE"
export const GET_PRIZE_SUCCESS = "GET_PRIZE_SUCCESS"
export const UPDATE_PRIZE = "UPDATE_PRIZE"
export const UPDATE_PRIZE_SUCCESS = "UPDATE_PRIZE_SUCCESS"

export const CREATE_PRIZE = "CREATE_PRIZE"
export const CREATE_PRIZE_SUCCESS = "CREATE_PRIZE_SUCCESS"


export const DELETE_PRIZE = "DELETE_PRIZE"
export const DELETE_PRIZE_SUCCESS = "DELETE_PRIZE_SUCCESS"