export const SUBMIT_FORM_DATA = "SUBMIT_FORM_DATA"
export const SUBMIT_FORM_DATA_SUCCESS = "SUBMIT_FORM_DATA_SUCCESS"
export const SUBMIT_FORM_DATA_ERROR = "SUBMIT_FORM_DATA_ERROR"

export const GET_SUBMISSION_FORM = "GET_SUBMISSION_FORM"
export const GET_SUBMISSION_FORM_SUCCESS = "GET_SUBMISSION_FORM_SUCCESS"

export const GET_DEFAULT_SUBMISSION = "GET_DEFAULT_SUBMISSION"
export const GET_DEFAULT_SUBMISSION_SUCCESS = "GET_DEFAULT_SUBMISSION_SUCCESS"

export const SUBMIT_DRAFT_SUBMISSIONS = "SUBMIT_DRAFT_SUBMISSIONS"
export const SUBMIT_DRAFT_SUBMISSIONS_SUCCESS = "SUBMIT_DRAFT_SUBMISSIONS_SUCCESS"

// export const GET_DEFAULT_SUBMISSION = "GET_DEFAULT_SUBMISSION"
// export const GET_DEFAULT_SUBMISSION_SUCCESS = "GET_DEFAULT_SUBMISSION_SUCCESS"