export const LOGIN_MESSAGE = "LOGIN_MESSAGE"
export const LOGIN_MESSAGE_SUCCESS = "LOGIN_MESSAGE_SUCCESS"

export const POST_FACEBOOK_IMAGE_MESSAGE = "POST_FACEBOOK_IMAGE_MESSAGE"
export const POST_FACEBOOK_IMAGE_MESSAGE_SUCCESS = "POST_FACEBOOK_IMAGE_MESSAGE_SUCCESS"


export const LOGOUT_MESSAGE = "LOGOUT_MESSAGE"
export const LOGOUT_MESSAGE_SUCCESS = "LOGOUT_MESSAGE_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"


export const RESET_LOGIN_FLAG = "RESET_LOGIN_FLAG"

export const GET_ORGANISATIONS = "GET_ORGANISATIONS"
export const GET_ORGANISATIONS_SUCCESS = "GET_ORGANISATIONS_SUCCESS"
