export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_INITIATE = "LOGIN_INITIATE"
export const LOGIN_CHALLENGE = "LOGIN_CHALLENGE"
export const LOGIN_CHALLENGE_SUCCESS = "LOGIN_CHALLENGE_SUCCESS"

export const REGISTER_INITIATE = "REGISTER_INITIATE"
export const REGISTER_CHALLENGE = "REGISTER_CHALLENGE"
export const REGISTER_CHALLENGE_SUCCESS = "REGISTER_CHALLENGE_SUCCESS"


export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_INITIATE_SUCCESS = "LOGIN_INITIATE_SUCCESS"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const API_ERROR = "LOGIN_API_ERROR"

export const SOCIAL_LOGIN = "SOCIAL_LOGIN"

export const RESET_LOGIN_FLAG = "RESET_LOGIN_FLAG"
